name: Release
on:
  release:
    types: [published,released]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: 'echo Hello, World!'
